from __future__ import annotations


def page() -> str:
    return '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><title>MAL-Updater</title><style>
:root{--bg:#08111f;--card:#111d31;--ink:#f5f7fb;--muted:#a9b6ca;--brand:#7c9cff;--ok:#54d39b;--bad:#ff7f91}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 85% 0,#172b55,var(--bg) 45%);color:var(--ink);font:16px/1.5 system-ui,sans-serif}header,main{max-width:72rem;margin:auto;padding:1.2rem}header{display:flex;justify-content:space-between;align-items:center}nav a{color:var(--ink);margin-left:1rem}section{background:rgba(17,29,49,.95);border:1px solid #263958;border-radius:18px;padding:clamp(1rem,3vw,2rem);margin:1rem 0;box-shadow:0 18px 60px #0005}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(17rem,1fr));gap:1rem}.pill{display:inline-block;border-radius:999px;padding:.25rem .65rem;background:#263958;color:var(--muted)}label{display:block;margin:.8rem 0 .25rem}input,button{width:100%;padding:.75rem;border-radius:9px;border:1px solid #405477;background:#0b1526;color:var(--ink);font:inherit}button{background:var(--brand);color:#071126;border:0;font-weight:750;cursor:pointer;margin-top:1rem}button.secondary{background:#263958;color:var(--ink)}button:focus,input:focus,a:focus{outline:3px solid #b4c5ff;outline-offset:2px}.message{min-height:1.5rem;color:var(--ok)}.error{color:var(--bad)}small{color:var(--muted)}@media(max-width:520px){header{align-items:flex-start;flex-direction:column}nav a{margin:0 1rem 0 0}}
</style></head><body><header><strong>◉ MAL-Updater</strong><nav><a href="/">Dashboard</a><a href="/settings">Settings</a></nav></header><main><p id="msg" class="message" role="status" aria-live="polite"></p>
<section id="dashboard"><span class="pill">Trusted LAN control plane</span><h1>Configuration</h1><div class="grid"><div><h2>Setup</h2><p id="setupState"></p></div><div><h2>Automation</h2><p id="automationState"></p><small>The scheduler starts automatically when MAL setup is complete.</small></div><div><h2>Connections</h2><p id="connections"></p></div></div><p><small>MAL writes remain conservative and are not enabled merely by onboarding.</small></p></section>
<section id="settings"><h1>Settings</h1><div class="grid"><form data-action="secrets"><h2>MAL application</h2><label>Client ID<input name="mal_client_id" autocomplete="off"></label><label>Client secret<input name="mal_client_secret" type="password" autocomplete="new-password"></label><button>Save credentials</button><button type="button" class="secondary" id="malTest">Test MAL connection</button><button type="button" class="secondary" id="oauth">Connect MAL account</button></form><form data-action="secrets"><h2>Provider credentials</h2><label>Crunchyroll username<input name="crunchyroll_username" autocomplete="username"></label><label>Crunchyroll password<input name="crunchyroll_password" type="password" autocomplete="new-password"></label><button>Save Crunchyroll</button><button type="button" class="secondary test" data-provider="crunchyroll">Test Crunchyroll</button><label>HIDIVE username<input name="hidive_username" autocomplete="username"></label><label>HIDIVE password<input name="hidive_password" type="password" autocomplete="new-password"></label><button>Save HIDIVE</button><button type="button" class="secondary test" data-provider="hidive">Test HIDIVE</button></form></div></section></main><script>
let csrf='';const $=x=>document.querySelector(x),msg=(t,e=false)=>{let m=$('#msg');m.textContent=t;m.className=e?'message error':'message'};async function api(path,body){let headers=body?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{};if(body&&!csrf)await bootstrap();let r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-CSRF-Token':csrf}:headers,body:body?JSON.stringify(body):null,cache:'no-store'});let j=await r.json().catch(()=>({error:'Unexpected response'}));if(!r.ok)throw Error((j.error||'Request failed').replaceAll('_',' '));return j}async function bootstrap(){let r=await fetch('/api/csrf',{cache:'no-store'}),j=await r.json();if(!r.ok||!j.csrf_token)throw Error('Unable to initialize request protection');csrf=j.csrf_token}async function refresh(){let [s,r]=await Promise.all([api('/api/settings'),api('/api/status')]);$('#setupState').textContent=s.setup_complete?'Complete':'Needs MAL configuration and OAuth';$('#automationState').textContent=r.automation_state==='running'?'Running':s.setup_complete?'Blocked while scheduler starts or restarts':'Blocked until MAL setup is complete';$('#connections').textContent=`MAL OAuth: ${s.mal_oauth_complete?'connected':'not connected'} · Crunchyroll: ${s.secrets_present.crunchyroll_username?'configured':'not configured'} · HIDIVE: ${s.secrets_present.hidive_username?'configured':'not configured'}`}document.addEventListener('submit',async e=>{e.preventDefault();let f=e.target,d=Object.fromEntries(new FormData(f));try{let replace={};for(let[k,v]of Object.entries(d))if(v)replace[k]=v;await api('/api/secrets',{replace,remove:[]});f.reset();msg('Credentials saved. They were not tested.');refresh()}catch(x){msg(x.message,true)}});$('#oauth').onclick=async()=>{try{let j=await api('/api/oauth/mal/start',{});location.href=j.authorization_url}catch(e){msg(e.message,true)}};document.querySelectorAll('.test').forEach(b=>b.onclick=()=>test(b.dataset.provider));$('#malTest').onclick=()=>test('mal');async function test(kind){try{let j=await api('/api/connections/test',{kind});msg(j.message||`${kind} connection succeeded`)}catch(e){msg(e.message,true)}}bootstrap().then(refresh).catch(e=>msg(e.message,true));
</script></body></html>'''
